apiVersion: skaffold/v3
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: ketanrtd1/auth
      context: .
      docker: 
        dockerfile: Dockerfile.authentication
      sync: 
        manual:
          - src: './*.go'
            dest: .
    - image: ketanrtd1/client
      context: .
      docker: 
        dockerfile: Dockerfile.client
      sync: 
        manual:
          - src: '**/*.js'
            dest: .